[package]
name = "sort"
version = "0.1.0"
authors = ["Egor <khromove@gmail.com>"]
edition = "2018"

[dev-dependencies]
criterion = "0.5"
shuffle = "0.1"
rand = "0.8"

[[bench]]
name = "sort"
harness = false
